/*
  RMIT University Vietnam
  Course: COSC2659 iOS Development
  Semester: 2022B
  Assessment: Assignment 1
  Author: Pham Hoang Thien An
  ID: s3818286
  Created  date: 2/8/2022
  Last modified: dd/mm/yyyy (e.g. 05/08/2022)
  Acknowledgement: Acknowledge the resources that you use here.
*/


import SwiftUI
import Foundation

var animes : [Anime] = [
    Anime(id: 111, name: "Shingeki no Kyojin - Attack on Titan", genre: "Drama, Shonen Manga", producer: "Wit Studio", broadcastYear: "2013", rating: 5, plot: "Shingeki no Kyojin, also known as Attack on Titan is an dark fantasy anime that take place in a world where the very last few  humanity are forced to live in a city surrounded by 3 huge walls to protect themselve from enourmous man-eating Titan. The story follows the path of Eren Yager, who vowed to exterminate every Titans that walk the Earth, and uncover the truth of the hidden world outside of the wall", review:"Attack on Titan is a very binge worthy anime, it is famous for its amazing character and story development, even the side characters are focused and developedto an extent that seeing one died brought us pain and sorrow. Though the action scenes in the anime are one of the best action in anime, viewers are also overwhelmed with the animation from the studios. Both studios did a good job bringing out the emotion of each character, and suck us into the flow of each battle, making us craving for more each time an episode ended.", imageName: "Attack_On_Titan_Image2", videoID: "LV-nazLVmgo"),
    
    Anime(id: 112, name: "Akame Ga KILL!", genre: "Drama, Dark fantasy", producer: "Square Enix", broadcastYear: "2012", rating: 4, plot:"Akame Ga Kill focus on Tatsumaki, a boy who set out to the Capital with his friends to find a way to earn money for their poor village. During his journey, he then learnt about the dark side of the Capital, a place where he thought that can make every dream come true. A Monarchy system that is filled with corrupted nobles that opress the poor to enrich themselve or simply to satisfy their selfish needs. After learning the truth, our main character then join forced with a rebel force whose vowed to end this corruption, one corrupted noble by one corrupted noble.", review:"Being produced by Square Enix, a famous japanese games and anime producer, it is quite understandable when the art in this anime is out of this world. Though the art of the anime is execellent, and each confrontation between each characters are memorable. I found what really captivate me is the story building and character development of the anime. For instance, in most anime, there are usually 2 side battling each other, the justice force vs the evil force. But in Akame ga Kill, when the 'justice' (The Capital army) fight will the 'evil' (the rebel). You will notice that the 'good guy' will use every possible dirty tricks to be able to exterminate the 'bad guy', like using civilians as hostage or meat shield, and many other methods.", imageName: "Akame_Ga_Kill_Image", videoID: "sCGWxQuSoDU"),
    
    Anime(id: 113, name: "Black Lagoon", genre: "Thriller, Adventure", producer: "Madhouse", broadcastYear: "2006", rating: 4, plot: "The series follows the Lagoon Company, a four-member team of pirate mercenaries smuggling goods in and around the seas of Southeast Asia with their PT boat, the Black Lagoon. The group takes on various jobs, usually involving criminal organizations and resulting in violent gunfights.", review:"lack Lagoon is an anime filled with guns, bloods, deaths and tons of excellent action sequences. Watching the show, aside from the satisfiable fighting scene and polished animation, viewers are also met with many questionable and disturbing story development, leaving the viewers with confusion and many question about the grim and dark world of Black Lagoon. Therefore, Black Lagoon won't be anyone's cup of tea, but with refined animation and amazing plot development, I think it is a must watch anime for any anime enjoyer.", imageName: "Black_Lagoon_Image", videoID: "V0pN6Yhbbrc"),
    
    Anime(id: 114, name: "Kimetsu no Yaiba - Demon Slayer", genre: "Dark fantasy, Thriller", producer: "Ufotable", broadcastYear: "2019", rating: 3, plot: "Tanjiro Kamado is a kind-hearted and intelligent boy who lives with his family in the mountains. He became his family's breadwinner after his father's death, making trips to the nearby village to sell charcoal. Everything changed when he came home one day to discover that his family was attacked and slaughtered by a demon. Tanjiro and his sister Nezuko were the sole survivors of the incident, with Nezuko being transformed into a demon, but still surprisingly showing signs of human emotion and thought. Both brother and sister then had start their adventure to find a cure for the little sister and save as many people from the same fate as they can.", review:"Kimetsu no Yaiba is one of the best action anime during its debut year, thanks to the effort of Ufotable producer team, each episode from the Anime is a big hit and able to shaken the anime community. Aside from that, the plot is pretty cliche and predictable, therefore, doesn't really give me any strong impression. If you are a fan of catchy and breath-taking anime fight scene, this is an anime for you.", imageName: "Kimetsu_No_Yaiba_Image", videoID: "VQGCKyvzIM4"),
    
    Anime(id: 115, name: "One-Punch Man", genre: "Action, Fiction, Comedy", producer: "Madhouse", broadcastYear: "2015", rating: 5, plot: "On a supercontinent Earth, powerful monsters and villains wreak havoc. The millionaire Agoni creates the Hero Association, which employs superheroes to fight evil. Saitama, an unassociated hero, hails from City Z and performs heroic deeds as a hobby. For three years, he has trained enough to defeat any enemy with a single punch, his unmatched strength leaving him bored. He becomes a reluctant mentor to Genos, a cyborg seeking revenge against another cyborg who killed his family and destroyed his hometown after saving him from a monster.", review:"When I first heard about One Punch Man from a friend, I thought that the anime is going to be another cliché anime with an overpowerful main character that can beat any villain standing in his way. After watching it for the first time, I mediately took back every word that I said. Though the anime main character can defeat every villain in one punch, it doesn’t affect the quality of the anime at all, since the anime itself focus more on the development of the side character and the justice ideal of the main character. Every side character in the anime is interesting and diverse, and it is satisfying to see them interacting with each other and the main character throughout the series. Furthermore, Madhouse being Madhouse, doesn't spare any manpower to polish the anime to perfection, every fighting scene is satisfyable to watch and the character design is breath-taking.", imageName: "One_Punch_Man_Image", videoID: "Poo5lqoWSGw"),
    
    Anime(id: 116, name: "Full Metal Alchemist", genre: "Adventure fiction", producer: "Madman Entertainment - Funimation Entertainment", broadcastYear: "2003", rating: 4, plot: "Fullmetal Alchemist takes place in the fictional country of Amestris. In this world, alchemy is one of the most-practiced sciences; alchemists who work for the government are known as State Alchemists and are automatically given the rank of major in the military. Alchemists have the ability, with the help of patterns called transmutation circles, to create almost anything they desire. However, when they do so, they must provide something of equal value in accordance with the Law of Equivalent Exchange. Edward and Alphonse Elric live in Resembool with their mother Trisha and father Van Hohenheim, the latter having left without a reason. Trisha soon dies from an illness. After finishing their alchemy training under Izumi Curtis, the Elrics attempt to bring their mother back with alchemy. The transmutation backfires, and Edward loses his left leg while Alphonse loses his body. Edward sacrifices his right arm to retrieve Alphonse's soul, binding it to a suit of armor.", review:"When I heard of 'Full Metal Alchemist' i didn't know what to expect! But only after watching the first episode I knew this series was special! From the start it drew me in and took me on a journey in to incredible adventures! It is the story that is truly amazing! At first the story is quite simple,but after a couple of episodes you will get some twists and turns you won't see coming! They managed to dazzle and surprise you almost every episode! Once you start watching 'Full Metal Alchemist' you will not stop! The anime successfully mixed different genres (sciencefiction,drama,action,horror and comedy)! Also FMA throws in some serious subjects for us to think about and be entertained at the same time! But what really makes this anime works are the characters! A lot of attention is paid to them! The good guys,the villains all have their good qualities and bad qualities! Evil characters don't have to be pure evil! And the good characters also make mistakes! In that sense most of the characters are very similar to us humans and therefore are very appealing! This anime sure will make an impact on you on different levels! A MUST SEE!", imageName: "Full_Metal_Alchemist_Image", videoID: "-GoNo0DGroU"),
    
    Anime(id: 117, name: "Kimi no Na Wa - Your Name", genre: "Romance, Drama", producer: "CoMix Wave films", broadcastYear: "2016", rating: 5, plot: "n 2013, Mitsuha Miyamizu is a high school girl living in the rural town of Itomori, Japan. Bored of the town, she wishes to be a Tokyo boy in her next life. One day, she inexplicably begins to switch bodies intermittently with Taki Tachibana, a high school boy in Tokyo. Thus, when they wake up as each other on some mornings, they must live through the other's respective activities and social interactions for the day. They learn they can communicate with each other by leaving messages on paper, phones, and sometimes on each other's skin.", review:"Your Name is just a good movie. This movie felt long, but not too long. All the way through, I was asking what would happen next. It was clever, emotional, and left me crying after the movie. The twist was done really well, and I almost wanted to pause the movie. Also, the animation is gorgeous. You get to see detailed images from many angles and perspectives, and there were hundreds of animators! The credits didn't start out with the cast like it usually would. The first thing you saw after a black screen was hundreds of names of animators and designers. I watched this movie again and I still felt my muscles ready to let tears out. I would not recommend this movie any less than the next guy, so what are you waiting for? Get a couple of friends and watch Your Name!", imageName: "Kimi_No_Nawa_Image", videoID: "_mifHzxFNQ4"),
    
    Anime(id: 118, name: "Mushoku Tensei - Jobless reincarnation", genre: "Adventure, Fantasy", producer: "Studio Bind", broadcastYear: "2021", rating: 4, plot: "An unnamed 34-year-old Japanese NEET is evicted from his home after failing to attend his parents' funeral. After some self-reflection, he concludes that his life is ultimately pointless. Still, he intercepts a speeding truck heading towards a group of teenagers in an attempt to do something noteworthy for the first time in his life. He pulls one of them out of harm's way just before he dies. He awakens in the body of a baby and discovers he has been reincarnated in a world of sword and sorcery. He resolves to succeed in his new life, abandoning his previous identity in place of Rudeus Greyrat. Rudeus develops a strong affinity for magic due to his aptitude and early training. He becomes a student of demon magician Roxy Migurdia during his youth, a friend of demihuman Sylphiette, and a teacher of magic to noble heiress Eris Boreas Greyrat. The story chronicles his new life's highlights as he attempts to overcome the failures of his previous one.", review:"This Isekai anime is one of my all time favourites the plot and characters are all interesting although the premise is not original it is executed very well considering all the garbage Isekai has to offer these days this one truly feels like you are immersed in the world with the main protagonist witnessing his growth with him and can I just say the animation and art style is just gorgeous very high tier I recommend this to anyone that enjoys a good story and visuals.", imageName: "Mushoku_Tensei_Image", videoID: "OS6KeVt1Ve0"),
    
    Anime(id: 119, name: "Naruto", genre: "Adventure, Comedy, Fantasy", producer: "Studio Pierrot", broadcastYear: "2002", rating: 5, plot: "Naruto tells the story of Naruto Uzumaki, a young ninja who seeks recognition from his peers and dreams of becoming the Hokage, the leader of his village. The story is told in two parts – the first set in Naruto's pre-teen years, and the second in his teens.", review:"One of the most popular shounen anime, which had sold over 250 millions editions from 1999 to 2014. In fact, the anime had an inspiring story that can attract every boy in the world. In particular, the main character named Naruto has a dream to become the Hokage - a person who has the most power in each country in the tough Ninja world. Moreover, to make the dream be true, Naruto overcome various difficult challenges and has to defeat tough enemies who want to destroy not only his country but also the Ninja World. Throughout his journey, by determination and genuinely, he has changed negative thinking from other people to him, making them accompany Naruto to make the Ninja world become better.", imageName: "Naruto_Image", videoID: "-G9BqkgZXRA"),
    
    Anime(id: 120, name: "Plastic Memory", genre: "Romane, Drama", producer: "Doga Bobo", broadcastYear: "2013", rating: 4, plot: "Eighteen-year-old Tsukasa Mizugaki has failed his college entrance exams, but after pulling some strings, he manages to land a job at the Sion Artificial Intelligence Corporation. SAI Corp is responsible for the creation of 'Giftias'—highly advanced androids which are almost indiscernible from normal humans. However, unlike humans, Giftias have a maximum lifespan of 81,920 hours, or around nine years and four months. Terminal Service One, the station Tsukasa was assigned to, is responsible for collecting Giftias that have met their expiration date, before they lose their memories and become hostile.Promptly after joining Terminal Service One, Tsukasa is partnered with a beautiful Giftia named Isla. She is a Terminal Service veteran and considered the best in Giftia retrievals, contrary to her petite figure and placid nature. Time is fleeting though, and Tsukasa must come to terms with his feelings for Isla before her time is up. No matter how much someone desires it, nothing lasts forever.", review:"This is a good example of a series that is very predictable without much twists, and yet is still able to satisfy the viewers until the end despite some flaws that go unnoticed, brought about by the weight of some solid moments, new ways of developing dialogues on the theme and a pint of jests. A lot of reviewers say that this series could have been expanded, that it really has potential in terms of its source material and subject matter. But I myself think that the anime has finished all ties and gave us a satisfy ending", imageName: "Plastic_Memory_Image", videoID: "vk6mg74R5Ek"),
]
