//
//  AnimeData.swift
//  s3818286_Assign1
//
//  Created by An Pham Hoang Thien on 02/08/2022.
//

import SwiftUI
import Foundation

var animes : [Anime] = [
    Anime(id: 111, name: "Shingeki no Kyojin - Attack on Titan", genre: "Drama, Shonen Manga", producer: "Wit Studio", broadcastYear: "2013", rating: 5, plot: "Plot: Shingeki no Kyojin, also known as Attack on Titan is an dark fantasy anime that take place in a world where the very last few  humanity are forced to live in a city surrounded by 3 huge walls to protect themselve from enourmous man-eating Titan. The story follows the path of Eren Yager, who vowed to exterminate every Titans that walk the Earth, and uncover the truth of the hidden world outside of the wall", review:"My thoughts: Attack on Titan is a very binge worthy anime, it is famous for its amazing character and story development, even the side characters are focused and developedto an extent that seeing one died brought us pain and sorrow. Though the action scenes in the anime are one of the best action in anime, viewers are also overwhelmed with the animation from the studios. Both studios did a good job bringing out the emotion of each character, and suck us into the flow of each battle, making us craving for more each time an episode ended.", imageName: "Attack_On_Titan_Image2", videoID: "LV-nazLVmgo"),
    
    Anime(id: 112, name: "Akame Ga KILL!", genre: "Drama, Dark fantasy", producer: "Square Enix", broadcastYear: "2012", rating: 4, plot:"Akame Ga Kill focus on Tatsumaki, a boy who set out to the Capital with his friends to find a way to earn money for their poor village. During his journey, he then learnt about the dark side of the Capital, a place where he thought that can make every dream come true. A Monarchy system that is filled with corrupted nobles that opress the poor to enrich themselve or simply to satisfy their selfish needs. After learning the truth, our main character then join forced with a rebel force whose vowed to end this corruption, one corrupted noble by one corrupted noble.", review:"Being produced by Square Enix, a famous japanese games and anime producer, it is quite understandable when the art in this anime is out of this world. Though the art of the anime is execellent, and each confrontation between each characters are memorable. I found what really captivate me is the story building and character development of the anime. For instance, in most anime, there are usually 2 side battling each other, the justice force vs the evil force. But in Akame ga Kill, when the 'justice' (The Capital army) fight will the 'evil' (the rebel). You will notice that the 'good guy' will use every possible dirty tricks to be able to exterminate the 'bad guy', like using civilians as hostage or meat shield, and many other methods.", imageName: "Akame_Ga_Kill_Image", videoID: "sCGWxQuSoDU"),
    
    Anime(id: 113, name: "Black Lagoon", genre: "Thriller, Adventure", producer: "Madhouse", broadcastYear: "2006", rating: 4, plot: " ", review:" ", imageName: "Black_Lagoon_Image", videoID: "V0pN6Yhbbrc"),
    
    Anime(id: 114, name: "Kimetsu no Yaiba - Demon Slayer", genre: "Dark fantasy, Thriller", producer: "Ufotable", broadcastYear: "2019", rating: 3, plot: " ", review:" ", imageName: "Kimetsu_No_Yaiba_Image", videoID: "VQGCKyvzIM4"),
    
    Anime(id: 115, name: "One-Punch Man", genre: "Action, Fiction, Comedy", producer: "Madhouse", broadcastYear: "2015", rating: 4, plot: " ", review:" ", imageName: "One_Punch_Man_Image", videoID: "Poo5lqoWSGw"),
    
    Anime(id: 116, name: "Full Metal Alchemist", genre: "Adventure fiction", producer: "Madman Entertainment - Funimation Entertainment", broadcastYear: "2003", rating: 4, plot: " ", review:" ", imageName: "Full_Metal_Alchemist_Image", videoID: "-GoNo0DGroU"),
    
    Anime(id: 117, name: "Kimi no Na Wa - Your Name", genre: "Romance, Drama", producer: "CoMix Wave films", broadcastYear: "2016", rating: 5, plot: " ", review:" ", imageName: "Kimi_No_Nawa_Image", videoID: "_mifHzxFNQ4"),
    
    Anime(id: 118, name: "Mushoku Tensei - Jobless reincarnation", genre: "Adventure, Fantasy", producer: "Studio Bind", broadcastYear: "2021", rating: 4, plot: " ", review:" ", imageName: "Mushoku_Tensei_Image", videoID: "OS6KeVt1Ve0"),
    
    Anime(id: 119, name: "Naruto", genre: "Adventure, Comedy, Fantasy", producer: "Studio Pierrot", broadcastYear: "2002", rating: 5, plot: "Naruto tells the story of Naruto Uzumaki, a young ninja who seeks recognition from his peers and dreams of becoming the Hokage, the leader of his village. The story is told in two parts – the first set in Naruto's pre-teen years, and the second in his teens.", review:"One of the most popular shounen anime, which had sold over 250 millions editions from 1999 to 2014. In fact, the anime had an inspiring story that can attract every boy in the world. In particular, the main character named Naruto has a dream to become the Hokage - a person who has the most power in each country in the tough Ninja world. Moreover, to make the dream be true, Naruto overcome various difficult challenges and has to defeat tough enemies who want to destroy not only his country but also the Ninja World. Throughout his journey, by determination and genuinely, he has changed negative thinking from other people to him, making them accompany Naruto to make the Ninja world become better.", imageName: "Naruto_Image", videoID: "-G9BqkgZXRA"),
    
    Anime(id: 120, name: "Plastic Memory", genre: "Romane, Drama", producer: "Doga Bobo", broadcastYear: "2013", rating: 4, plot: "Eighteen-year-old Tsukasa Mizugaki has failed his college entrance exams, but after pulling some strings, he manages to land a job at the Sion Artificial Intelligence Corporation. SAI Corp is responsible for the creation of 'Giftias'—highly advanced androids which are almost indiscernible from normal humans. However, unlike humans, Giftias have a maximum lifespan of 81,920 hours, or around nine years and four months. Terminal Service One, the station Tsukasa was assigned to, is responsible for collecting Giftias that have met their expiration date, before they lose their memories and become hostile.Promptly after joining Terminal Service One, Tsukasa is partnered with a beautiful Giftia named Isla. She is a Terminal Service veteran and considered the best in Giftia retrievals, contrary to her petite figure and placid nature. Time is fleeting though, and Tsukasa must come to terms with his feelings for Isla before her time is up. No matter how much someone desires it, nothing lasts forever.", review:"This is a good example of a series that is very predictable without much twists, and yet is still able to satisfy the viewers until the end despite some flaws that go unnoticed, brought about by the weight of some solid moments, new ways of developing dialogues on the theme and a pint of jests. A lot of reviewers say that this series could have been expanded, that it really has potential in terms of its source material and subject matter. But I myself think that the anime has finished all ties and gave us a satisfy ending", imageName: "Plastic_Memory_Image", videoID: "vk6mg74R5Ek"),
]
